name: Maps
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  compile_all_maps:
    name: Compile Maps
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Setup cache
        id: cache-byond
        uses: actions/cache@v2
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-cache-${{ hashFiles('Dockerfile') }}
      - name: Install BYOND
        if: steps.cache-byond.outputs.cache-hit != 'true'
        run: bash tools/ci/install_byond.sh
      - name: Compile All Maps
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          tools/bootstrap/python tools/ci/template_dm_generator.py
          tgui/bin/tgui --build
          bash tools/ci/dm.sh -DCIBUILDING -DCITESTING -DALL_MAPS shiptest.dme

